// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTarget(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function Chat(arg1:string,arg2:string):Promise<string>;

export function ConfirmTool(arg1:boolean):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function FetchModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetConfigDir():Promise<string>;

export function GetCurrentConfig():Promise<Record<string, any>>;

export function GetInfo():Promise<Record<string, any>>;

export function ListConversations():Promise<Array<main.ConversationInfo>>;

export function ListTargets():Promise<Array<Record<string, any>>>;

export function ListTools():Promise<Array<main.ToolInfo>>;

export function ProbeProviders():Promise<Array<main.ProviderInfo>>;

export function ProbeTarget(arg1:string):Promise<Record<string, any>>;

export function RemoveTarget(arg1:string):Promise<string>;

export function SaveLLMConfig(arg1:string,arg2:string,arg3:string):Promise<string>;
