// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddTarget'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Chat(arg1, arg2) {
  return window['go']['main']['App']['Chat'](arg1, arg2);
}

export function ConfirmTool(arg1) {
  return window['go']['main']['App']['ConfirmTool'](arg1);
}

export function CreateEmptyConversation() {
  return window['go']['main']['App']['CreateEmptyConversation']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessage'](arg1, arg2);
}

export function DeleteMessagesFrom(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessagesFrom'](arg1, arg2);
}

export function EditMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2, arg3);
}

export function FetchModels(arg1, arg2) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2);
}

export function GetAvailableSources() {
  return window['go']['main']['App']['GetAvailableSources']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetConversationMessages(arg1) {
  return window['go']['main']['App']['GetConversationMessages'](arg1);
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function GetToolConfig(arg1) {
  return window['go']['main']['App']['GetToolConfig'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListTargets() {
  return window['go']['main']['App']['ListTargets']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function ProbeProviders() {
  return window['go']['main']['App']['ProbeProviders']();
}

export function ProbeTarget(arg1) {
  return window['go']['main']['App']['ProbeTarget'](arg1);
}

export function RegenerateFrom(arg1, arg2) {
  return window['go']['main']['App']['RegenerateFrom'](arg1, arg2);
}

export function RemoveTarget(arg1) {
  return window['go']['main']['App']['RemoveTarget'](arg1);
}

export function SaveLLMConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1, arg2, arg3);
}

export function SaveProxy(arg1) {
  return window['go']['main']['App']['SaveProxy'](arg1);
}

export function StopChat() {
  return window['go']['main']['App']['StopChat']();
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function UpdateToolConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateToolConfig'](arg1, arg2, arg3);
}

export function UploadSpec() {
  return window['go']['main']['App']['UploadSpec']();
}
